### ISSUE TITLE
Guía de instalación

### ISSUE THREAD

**Issue by kaiserdj** [FSVera/Trackime#4]
Podrías indicar como se instala, o una explicación breve por donde empezar.
Gracias

PD: Parece un proyecto muy interesante

**Comment by FernandoSilvaVera** [comment]
Hola! no había visto tu mensaje

tengo pendiente hacer una guía para instalar el proyecto pero no he tenido mucho tiempo jeje.
Prueba lo siguiente

1.- ejecutar el fichero install
2.- rellenar los datos de la base de datos en .env
3.- ejecutar el sql dentro de la carpeta database (bbdd.sql)

Con esos pasos ya puedes ver la aplicación (Hay algunos animes que están rotos, por que la página donde se guardaban se ha migrado y por pruebas varias)

Si tienes un usuario Administrador, puedes agregar animes desde animeflv, aunque lo he estado modificando un poco y no funciona bien, tengo que arreglarlo

Espero que te funcione, me avisas si te falla en alguna parte

Saludos!

**Comment by kaiserdj** [comment]
Okey muchas gracias
