### ISSUE TITLE
Bug dominio

### ISSUE THREAD

**Issue by kaiserdj** [FSVera/Trackime#6]
El direccionamiento url de ficheros y enlaces no añaden sub-carpetas, solo el dominio principal:
Ejemplo de error:
- Actual:
>  `<a href="/watch?anime=sword art online alicization war of underworld&amp;capitulo=1"><img src="/images/sword-art-online-alicization-war-of-underworld.jpg" class="card-img-top"></a>`

- Correcto:
>  `<a href="/public/watch?anime=sword art online alicization war of underworld&amp;capitulo=1"><img src="/public/images/sword-art-online-alicization-war-of-underworld.jpg" class="card-img-top"></a>`

![image](https://user-images.githubusercontent.com/5487950/69423226-dbc08600-0d25-11ea-8ab2-27aaad15a31b.png)
![image](https://user-images.githubusercontent.com/5487950/69423378-3bb72c80-0d26-11ea-886a-23b4579a6a81.png)

*Y las imágenes, las tengo añadidas

**Comment by FernandoSilvaVera** [comment]
Está configurado de esa forma, para no mostrar la carpeta public en la url, puedes usar el server que tiene laravel -> php artisan serv

![image](https://user-images.githubusercontent.com/22908370/69481435-a09b8100-0e11-11ea-89a7-a15d704d48f0.png)

en mi caso tengo configurado apache2 para que entre directamente en la carpeta public

![image](https://user-images.githubusercontent.com/22908370/69481455-c759b780-0e11-11ea-9301-5d099ba58c9b.png)

**Comment by kaiserdj** [comment]
En windows para que funcione bien con xampp, añadiendo esto me a funcionado:
-F:\xampp\apache\conf\extra\httpd-vhosts.conf
```
<VirtualHost *:80>
DocumentRoot "F:\xampp\htdocs\Trackime\public"
ServerName Trackime.com
<Directory "F:\xampp\htdocs\Trackime\public">
</Directory>
</VirtualHost>
```
-C:\Windows\System32\drivers\etc\hosts
`127.0.0.1      Trackime.com`
