### ISSUE TITLE
Error al importar bbdd

### ISSUE THREAD

**Issue by kaiserdj** [FSVera/Trackime#7]
Al intentar importar la ultima versión de la bbdd en un servidor mysql:
- Apache/2.4.38 (Win64) OpenSSL/1.1.1b PHP/7.3.2
- Versión del servidor: 10.1.38-MariaDB
- Versión del cliente de base de datos: libmysql - mysqlnd 5.0.12-dev - 20150407
- Versión de PHP: 7.3.2 

![image](https://user-images.githubusercontent.com/5487950/69487496-38718d00-0e5b-11ea-9f68-a101d31b1dc9.png)

**Comment by FernandoSilvaVera** [comment]
Imagino que será por al diferencia en la base de datos, prueba a cambiar los varchar 255, por unos 100 o menos

**Comment by kaiserdj** [comment]
Cambiando todos los `varchar(255)` a `varchar(100)`
Funciona perfectamente
